### ISSUE TITLE
[<milestone>] <description>

### ISSUE THREAD

**Issue by gomete** [pezaio/.github#2]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have added the milestone
- [X] I have added to a project
- [X] I have searched existing issues to ensure a similar issue has not already been created

### Context

Lorem ipsum

### Depends on

- [ ] #1

### Acceptance Criteria

- [ ] Acceptance Criteria 1
- [ ] Acceptance Criteria 2

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
